project:
  type: website
  output-dir: _site
bibliography: references.bib
  resource-path: ["."]
website:
  title: "Semih Cayci"
  site-url: https://semihcayci.github.io/
  description: "Math-friendly blog powered by Quarto"
  
  navbar:
    right:
      - text: Posts
        href: posts/index.qmd
      - text: About
        href: about.qmd
  page-footer:
    left: "© 2025 Semih Cayci"
    right: "Built with Quarto"
  repo-url: https://github.com/semihcayci/semihcayci.github.io
  repo-actions: [issue]

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-copy: true
    smooth-scroll: true
    html-math-method: mathjax

execute:
  freeze: auto
  echo: false
