project:
  type: website
  output-dir: _site

# Top-level project-wide settings
bibliography: references.bib
resource-path: ["."]
execute:
  freeze: auto
  echo: false

website:
  title: "Notes on Theoretical RL"
  site-url: https://semihcayci.github.io/
  navbar:
    right:
      - text: Posts
        href: posts/index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-copy: true
    html-math-method: mathjax
